import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul>
          <li>
            <Link href="/profile">profile</Link>
          </li>
          <li>
            <Link href="/">Home</Link>
          </li>
        </ul>
        <div style={{ height: 100 }} />
        {children}
      </body>
    </html>
  );
}
